const links = [
  {
    title: "About",
    name: "about",
    to: "/#about",
    requiresLogin: false,
    alwaysShow: false,
  },
  {
    title: "Browse",
    name: "browse",
    to: "/browse",
    requiresLogin: false,
    alwaysShow: true,
  },
  {
    title: "Host",
    name: "host",
    to: "/my-stores",
    requiresLogin: false,
    alwaysShow: false,
  },
  {
    title: "Login",
    name: "login",
    to: "/login",
    requiresLogin: false,
    alwaysShow: false,
  },
  {
    title: "Sign up",
    name: "sign-up",
    to: "/sign-up",
    requiresLogin: false,
    alwaysShow: false,
  },
  {
    title: "Saved items",
    name: "saved-items",
    to: "/app",
    requiresLogin: true,
    alwaysShow: false,
  },
  {
    title: "My Stores",
    name: "my-stores",
    to: "/my-stores",
    requiresLogin: true,
    alwaysShow: false,
  },
  {
    title: "Account",
    name: "account",
    to: "/app",
    requiresLogin: true,
    alwaysShow: false,
  },
  {
    title: "Log out",
    name: "logout",
    to: "/login",
    requiresLogin: true,
    alwaysShow: false,
  },
];
